### ISSUE TITLE
Some changes are required in Portfolio Website

### ISSUE THREAD

**Issue by umair-rao** [ernestkorir/my-portfolio#7]
You have built a great and appealing Portfolio Website but if you may consider some more suggestions it will have a great impact on your layout.

- Margins may be checked to make the site more responsive.
- Background image location may be improved by making it more responsive.

**Comment by boo-shehab** [comment]
- you did a great job but you have another litter issue with the language class it's will be better if you removed the width from it and from the language ul li too

**Comment by ernestkorir** [comment]
Rsolved
